# Workflow from https://github.com/python-docs-translations/transifex-automations/blob/main/sample-workflows/transifex-pull.yml
name: Pull Translations from Transifex

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-translation:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ '3.14' ]
    steps:
      - uses: styfle/cancel-workflow-action@main
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@master
        with:
          python-version: 3
      - name: Install Dependencies
        run: |
          sudo apt-get install -y gettext
          pip install requests cogapp polib transifex-python sphinx-intl blurb six
          curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash
        working-directory: /usr/local/bin
      - uses: actions/checkout@master
        with:
          ref: ${{ matrix.version }}
          fetch-depth: 0
      - run: curl -O https://raw.githubusercontent.com/python-docs-translations/transifex-automations/master/sample-workflows/transifex-util.py
      - run: chmod +x transifex-util.py
      - run: ./transifex-util.py recreate_tx_config --language id --project-slug python-newest --version 3.14
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
      - run: ./transifex-util.py fetch --language id --project-slug python-newest --version 3.14
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
      - run: ./transifex-util.py delete_obsolete_files --language id --project-slug python-newest --version 3.14
      - name: Set up Git
        run: |
          git config --local user.email github-actions@github.com
          git config --local user.name "GitHub Action's update-translation job"
      - name: Filter files
        run: |
          ! git diff -I'^"POT-Creation-Date: ' \
                     -I'^"Language-Team: ' \
                     -I'^# ' -I'^"Last-Translator: ' \
                     --exit-code \
            && echo "SIGNIFICANT_CHANGES=1" >> $GITHUB_ENV || exit 0
      - run: git add .
      - run: git commit -m 'Update translation from Transifex'
        if: env.SIGNIFICANT_CHANGES
      - uses: ad-m/github-push-action@master
        if: env.SIGNIFICANT_CHANGES
        with:
          branch: ${{ matrix.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
